
name: Test Actions

on:
  workflow_dispatch:

env: 
  api_key: ${{ secrets.API_KEY }}
  api_secret: ${{ secrets.API_SECRET }}
  proxy_url: ${{ secrets.PROXY_URL }}
  

jobs:
  test_server_ip:     
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Test
      run: python main.py
     
